services:
  # Servizio per il database PostgreSQL
  pgs:
    container_name: pgs
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin


  # Servizio per il server Express
  app:
    build: 
      context: ./db_services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - pgs

