version: '3.8'
services:
  # Servizio per il database PostgreSQL
  pgs:
    container_name: pgs
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    #volumes:
      #- ./dataset_&_modelli:/app/dataset_&_modelli


  # Servizio per il server Express
  app:
    build: 
      context: ./db_services
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      pgs:
        condition: service_healthy
    volumes:
      - ./dataset_&_modelli:/app/dataset_&_modelli
      - ./.env:/app/.env
